#!/usr/bin/env bash

source /usr/share/yunohost/helpers

main() {
  ynh_abort_if_errors

  local app=$YNH_APP_INSTANCE_NAME
  local domain=$(ynh_app_setting_get $app domain)
  local path=$(ynh_app_setting_get $app path)
  local deploy_path=$(ynh_app_setting_get $app deploy_path)
  local backup_dir=$YNH_APP_BACKUP_DIR
  local nginx_conf=/etc/nginx/conf.d/$domain.d/$app.conf

  ynh_backup $deploy_path "sources"

  sudo mkdir --parent ./conf
  ynh_backup $nginx_conf "conf/nginx.conf"
}

main
