#!/usr/bin/env bash

# Exit on command errors 
# set -o errexit 
# Treat unset variables as an error
# set -o nounset
set -eu

source /usr/share/yunohost/helpers
source .hfunctions

#
# With reference to https://github.com/YunoHost/yunohost/pull/234/files
# TODO: remove me ynh_normalize_path is in stable 
#
ynh_normalize_path() {
 local path=$1

 if [ "${path:0:1}" != "/" ]; then
   path="/$path"
 fi
 if [ "${path:${#path}-1}" == "/" ] && [ ${#path} -gt 1 ]; then
   path="${path:0:${#path}-1}"
 fi
 echo $path
}

main() {
  local app=$YNH_APP_INSTANCE_NAME
  local is_public=$YNH_APP_ARG_IS_PUBLIC
  local domain=$YNH_APP_ARG_DOMAIN
  local path=$(ynh_normalize_path $YNH_APP_ARG_PATH)
  local deploy_path=/var/www/$app
  local app_config=../conf/app.src #should we make this a convention?
  local nginx_config_template=../conf/nginx.conf
  local url=$domain$path
  local source_version=$(app_config_get $app_config "SOURCE_VERSION")

  ynh_app_setting_set $app is_public $is_public
  ynh_app_setting_set $app domain $domain
  ynh_app_setting_set $app path $path
  ynh_app_setting_set $app url $url
  ynh_app_setting_set $app deploy_path $deploy_path
  ynh_app_setting_set $app app_version $source_version

  sudo yunohost app checkurl $url -a $app 

  obtain_and_deploy_source $app_config $deploy_path
  update_nginx_configuration $app $nginx_config_template $domain $path $deploy_path
  update_accessibility $app $is_public
}

main
