#!/usr/bin/env bash

source /usr/share/yunohost/helpers
source _common.sh

main() {
  ynh_abort_if_errors

  local app=$YNH_APP_INSTANCE_NAME
  local is_public=$YNH_APP_ARG_IS_PUBLIC
  local domain=$YNH_APP_ARG_DOMAIN
  local path=$YNH_APP_ARG_PATH
  local deploy_path=/var/www/$app
  local nginx_config_template=../conf/nginx.conf
  local url=$domain$path
  local path=$(ynh_normalize_url_path $path)

  ynh_webpath_available $domain $path
  ynh_webpath_register $app $domain $path

  ynh_app_setting_set $app is_public $is_public
  ynh_app_setting_set $app domain $domain
  ynh_app_setting_set $app path $path
  ynh_app_setting_set $app url $url
  ynh_app_setting_set $app deploy_path $deploy_path

  ynh_setup_source $deploy_path

  update_nginx_configuration $app $nginx_config_template $domain $path $deploy_path
  update_accessibility $app $is_public
}

main
