#!/usr/bin/env bash
set -u

source /usr/share/yunohost/helpers

main() {
  local app=${YNH_APP_INSTANCE_NAME}
  local domain=$(ynh_app_setting_get $app domain)
  local deploy_path=$(ynh_app_setting_get $app deploy_path)
  local nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"

  ynh_secure_remove $deploy_path
  ynh_secure_remove $nginx_conf

  sudo service nginx reload
}

main
